### ISSUE TITLE
Sudoku-Solver

### ISSUE THREAD

**Issue by Shishirr17** [pujazha/Hactoberfest2023#36]
A 9×9 incomplete sudoku, solve it such that it becomes valid sudoku. Valid sudoku has the following properties.

         1. All the rows should be filled with numbers(1 – 9) exactly once.

         2. All the columns should be filled with numbers(1 – 9) exactly once.

         3. Each 3×3 submatrix should be filled with numbers(1 – 9) exactly once.

**Comment by AnkitaGupta2002** [comment]
Hey, I would like to contribute in this.!!

**Comment by Jugnu-Gupta** [comment]
please assign me this under hacktoberfest2023!!
i have good knowledge of DSA.

**Comment by pujazha** [comment]
Okay
