### ISSUE TITLE
Password generator, a number guessing game, a quiz game, and a basic calculator in Python

### ISSUE THREAD

**Issue by Maryam0330** [pujazha/Hactoberfest2023#43]
I am writing to propose a contribution to the Python project. I have developed four Python projects that can be used for various purposes: a password generator, a number guessing game, a quiz game, and a basic calculator.
The password generator creates strong passwords that are difficult to guess. The number guessing game is a simple game where the user tries to guess a random number. The quiz game is a more complex game where the user answers questions on a variety of topics. The basic calculator is a simple calculator that can perform basic arithmetic operations.
I believe that these projects would be a valuable addition to the Python project. They would provide users with a variety of tools that they can use for different purposes.

**Comment by pujazha** [comment]
> I am writing to propose a contribution to the Python project. I have developed four Python projects that can be used for various purposes: a password generator, a number guessing game, a quiz game, and a basic calculator. The password generator creates strong passwords that are difficult to guess. The number guessing game is a simple game where the user tries to guess a random number. The quiz game is a more complex game where the user answers questions on a variety of topics. The basic calculator is a simple calculator that can perform basic arithmetic operations. I believe that these projects would be a valuable addition to the Python project. They would provide users with a variety of tools that they can use for different purposes.

okay
