### ISSUE TITLE
Snake water gun game in java

### ISSUE THREAD

**Issue by MohammadRehanPatel** [pujazha/Hactoberfest2023#61]

**Comment by MohammadRehanPatel** [comment]
Please Assign me this issue with hactoberfest tags

**Comment by sumitverma107** [comment]
HI @pujazha please assign this to me.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by nikhilgupta0** [comment]
please assign to me .i want to contribute in this . with hacktober tags
